# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtpzRRTeuUouGMqL1mIX1X-eRAQBW866
"""

# Commented out IPython magic to ensure Python compatibility.
# Authorize access to mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
!pip install tensorflow==2.12.0
import tensorflow as tf
try:
#     %tensorflow_version 2.x
except:
    pass

print('Using TensorFlow Version:', tf.__version__)

import tensorflow.keras.backend as K
from tensorflow import GradientTape

from tensorflow.image import resize
from tensorflow.keras import Input
from tensorflow.keras.models import Model
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import GlobalAveragePooling2D, Flatten, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import Precision, Recall
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, TensorBoard

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.metrics import roc_curve, roc_auc_score, precision_recall_curve, average_precision_score, PrecisionRecallDisplay

import os
from pathlib import Path
import csv
import nibabel as nib
import datetime

import numpy as np
import matplotlib.pyplot as plt
import cv2

! pip install -U resnet_rs
# from tensorflow.keras.applications.resnet_rs import ResNetRS50
# from tensorflow.keras.applications.resnet_v2 import ResNet50V2
# from tensorflow.keras.applications.densenet import DenseNet121
from tensorflow.keras.applications.mobilenet import MobileNet
# from tensorflow.keras.applications.vgg19 import VGG19
# from keras.applications.inception_v3 import InceptionV3
# from keras.applications.inception_resnet_v2 import InceptionResNetV2
# from keras.applications.xception import Xception
# from keras.applications.nasnet import NASNetLarge
# from keras.applications import MobileNetV3Large
# from keras.applications import MobileNetV3Small
# from keras.applications.densenet import DenseNet169
# from keras.applications.densenet import DenseNet201
# from keras.applications.efficientnet import EfficientNetB0
# from keras.applications.efficientnet_v2 import EfficientNetV2L
# from keras.applications.regnet import RegNetX002
# from keras.applications.convnext import ConvNeXtBase
# from keras.applications.mobilenet import MobileNet
# from keras.applications.mobilenet_v3 import MobileNetV3
# from keras.applications.regnet import RegNetY006

def crop_noise(img_path=None, img_array=None, plot=False):
    if img_path is not None:
        img = cv2.imread(img_path)
        img2 = img.copy()
    else:
        img = img_array
        img2 = img_array.copy()

    grayscale_img = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    smoothed_img = cv2.GaussianBlur(grayscale_img, (5, 5), 0)

    binary_img = cv2.threshold(smoothed_img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

    kernel = np.ones((8, 8), dtype=np.uint8)
    eroded_img = cv2.erode(binary_img, kernel, iterations=1)
    dilated_img = cv2.dilate(eroded_img, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(dilated_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    areas = [cv2.contourArea(contour) for contour in contours]

    max_index = np.argmax(areas)
    contour = contours[max_index]
    cv2.drawContours(img2, contours, -1, (0, 255, 0), 3)

    x, y, w, h = cv2.boundingRect(contour)
    xmin = x
    xmax = x + w
    ymin = y
    ymax = y + h
    cv2.rectangle(img2, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)

    cropped_img = img[ymin:ymax, xmin:xmax]

    if plot:
        fig, axs = plt.subplots(nrows=1, ncols=7, figsize=(24, 4), constrained_layout=True)

        for i, img_filter in enumerate(['Grayscale', 'Smoothed', 'Binary', 'Eroded', 'Dilated', 'Contoured', 'Cropped']):
            axs[i].set_title(img_filter)

        axs[0].imshow(grayscale_img)
        axs[1].imshow(smoothed_img)
        axs[2].imshow(binary_img)
        axs[3].imshow(eroded_img)
        axs[4].imshow(dilated_img)
        axs[5].imshow(img2)
        axs[6].imshow(cropped_img)

        plt.show()

    return cropped_img

def create_model1(print_summary=False):
    # Instantiate a base model with pre-trained weights
    base_model = MobileNet(weights='imagenet',
                                include_top=False,
                                input_shape=(224,224,3))
    # Freeze the base model
    for layer in base_model.layers:
        layer.trainable = False

    x = base_model.output

    # Add new layers to the end of the base model
    x = GlobalAveragePooling2D()(x)
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)

    # Add a final dense layer with a single neuron (logistic regression)
    predictions = Dense(4, activation="softmax")(x)

    model = Model(inputs=base_model.inputs, outputs=predictions)

    if print_summary:
        model.summary()

    return model

METRICS = ['accuracy',
           Precision(name='precision'),
           Recall(name='recall')]

def compile_model(model):
    model.compile(loss='categorical_crossentropy',
                  optimizer=Adam(learning_rate=0.0006),
                  metrics=METRICS)

model1 = create_model1(print_summary=True)
compile_model(model1)

model = load_model(r'/content/drive/MyDrive/archive (1)/models/MobileNetFix')
testingPath = r"/content/drive/MyDrive/archive (1)/Testing"
#test_datagen = ImageDataGenerator(rescale = 1./255)
#testingGenerator = test_datagen.flow_from_directory(directory = testingPath, color_mode = "rgb", shuffle = False, class_mode = "categorical")
test_datagen = ImageDataGenerator(rescale = 1./255, preprocessing_function = crop_noise_pre) # /255 cuz the function wont do anything without params
testingGenerator = test_datagen.flow_from_directory(directory = testingPath, color_mode = "rgb", shuffle = False, class_mode = "categorical", target_size = (224,224), batch_size=BATCH_SIZE)
batch = testingGenerator.next()
# batch = testingGenerator.next()
img_batch = batch[0]
img_index = 1 # random image from the image_batch taken from ImageDataGenerator
img_array = (img_batch[img_index] * 255).astype(np.uint8)
resized_img = np.asarray(resize(crop_noise(img_array=img_array), (224, 224))).astype(np.uint8)
# np.seterr(divide='ignore', invalid='ignore')
# resized_img = resized_img / 255

predictions1 = model.predict(testingGenerator)

def predict(img_index):
  fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(14, 14), constrained_layout=True)
  axs[0].imshow(img_array)
  axs[1].imshow(resized_img)
  plt.show()
  prediction = batch[1][img_index]
  for i in range(4):
    if prediction[i] == 1:
      if i == 0:
        print("Glioma")
      elif i == 1:
        print("Meningioma")
      elif i == 2:
        print("Normal")
      elif i == 3:
        print("Pituitary")
  print(predictions1[img_index])
  index = np.argmax(predictions1[img_index])
  if index == 0:
    print("Glioma")
  elif index == 1:
    print("Meningioma")
  elif index == 2:
    print("Normal")
  elif index == 3:
    print("Pituitary")

from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

label = []
for x in range(41):
  for i in range(len(batch[1])):
    index = np.argmax(batch[1][img_index])
    label.append(index)
    if index == 0:
      print("Glioma")
    elif index == 1:
      print("Meningioma")
    elif index == 2:
      print("Normal")
    elif index == 3:
      print("Pituitary")
  batch = testingGenerator.next()
print(label)

predictions = []
for i in range(1311):
  index = np.argmax(predictions1[i])
  predictions.append(index)
  if index == 0:
    print("Glioma")
  elif index == 1:
    print("Meningioma")
  elif index == 2:
    print("Normal")
  elif index == 3:
    print("Pituitary")
print(predictions)

print(label)
print(predictions)
y_pred = predictions
y_test = label
labels = ["Glioma", "Meningioma", "Normal", "Pituitary"]

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)

disp.plot(cmap=plt.cm.Blues)
plt.show()

from tensorflow.keras.applications.mobilenet import preprocess_input, decode_predictions

# Choose the layer from which to extract the feature maps
last_conv_layer = model.get_layer('conv_pw_13')

# Define a model that outputs the feature maps and predictions
grad_model = tf.keras.models.Model(
    [model.inputs], [last_conv_layer.output, model.output]
)

# Function to perform Grad-CAM
def grad_cam(input_image):
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(preprocess_input(input_image.reshape(1,224,224,3)))
        loss = predictions[:, np.argmax(predictions[0])]

    grads = tape.gradient(loss, conv_outputs)[0]
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    heatmap = tf.reduce_mean(tf.multiply(pooled_grads, conv_outputs[0]), axis=-1)
    heatmap = tf.maximum(heatmap, 0)
    heatmap /= np.max(heatmap)
    return heatmap.numpy()

# Perform Grad-CAM
# heatmap = grad_cam(resized_img) # INSERT TESTING IMAGE ARRAY HERE AND CALL IT "img"


# heatmap = cv2.resize(heatmap, (resized_img.shape[0], resized_img.shape[1]))
# heatmap = np.uint8(heatmap)
# heatmap = cv2.applyColorMap(np.uint8(heatmap), cv2.COLORMAP_JET)

# # Superimpose the heatmap on the original image
# superimposed_img = heatmap * 0.04 + resized_img
# plt.imshow(superimposed_img)
# plt.show()

def GRAD(img_index):
  # Perform Grad-CAM
  heatmap = grad_cam(resized_img)

  # Resize the heatmap to match the input image size
  heatmap = cv2.resize(heatmap, (resized_img.shape[1], resized_img.shape[0]))

  # Normalize the heatmap
  heatmap = (heatmap - np.min(heatmap)) / (np.max(heatmap) - np.min(heatmap) + 1e-10)

  # Convert to the range [0, 255] for visualization
  heatmap = (255 * heatmap).astype("uint8")

  # Apply a colormap
  heatmap_colored = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

  # Superimpose the heatmap on the original image
  superimposed_img = cv2.addWeighted(resized_img, 1, heatmap_colored, 0.6, 0) # first num and second num is aplha and beta, which is how much is used from each respective image

  # Display the result
  fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(14, 14), constrained_layout=True)
  axs[0].imshow(superimposed_img)
  axs[1].imshow(resized_img)
  plt.show()

img_index = 11;
predict(img_index)
GRAD(img_index)

from tensorflow.keras.applications.mobilenet import preprocess_input, decode_predictions

# Choose the layer from which to extract the feature maps
last_conv_layer = model.get_layer('conv_pw_13')

# Define a model that outputs the feature maps and predictions
grad_model = tf.keras.models.Model(
    [model.inputs], [last_conv_layer.output, model.output]
)

# Function to perform Grad-CAM
def grad_cam(input_image):
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(preprocess_input(input_image.reshape(1,224,224,3)))
        loss = predictions[:, np.argmax(predictions[0])]

    grads = tape.gradient(loss, conv_outputs)[0]
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    heatmap = tf.reduce_mean(tf.multiply(pooled_grads, conv_outputs[0]), axis=-1)
    heatmap = tf.maximum(heatmap, 0)
    heatmap /= np.max(heatmap)
    return heatmap.numpy()

# Perform Grad-CAM
heatmap = grad_cam(resized_img)
heatmap = cv2.resize(heatmap, (resized_img.shape[1], resized_img.shape[0]))
heatmap = (heatmap - np.min(heatmap)) / (np.max(heatmap) - np.min(heatmap) + 1e-10)
heatmap = (255 * heatmap).astype("uint8")
heatmap_colored = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
superimposed_img = cv2.addWeighted(resized_img, 1, heatmap_colored, 0.6, 0)

# Display the result
fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(14, 14), constrained_layout=True)
axs[0].imshow(superimposed_img)
axs[1].imshow(resized_img)
plt.show()

model = load_model(r'/content/drive/MyDrive/archive (1)/models/MobileNetFix')
testingPath = r"/content/drive/MyDrive/archive (1)/Testing"
BATCH_SIZE = 32
#test_datagen = ImageDataGenerator(rescale = 1./255)
#testingGenerator = test_datagen.flow_from_directory(directory = testingPath, color_mode = "rgb", shuffle = False, class_mode = "categorical")
test_datagen = ImageDataGenerator(rescale = 1./255, preprocessing_function = crop_noise_pre) # /255 cuz the function wont do anything without params
testingGenerator = test_datagen.flow_from_directory(directory = testingPath, color_mode = "rgb", shuffle = False, class_mode = "categorical", target_size = (224,224), batch_size=BATCH_SIZE)
prednum = 0
for j in range(10):
  for k in range(j+1):
    batch = testingGenerator.next()
    print("batch: " + str(j+1))
    for e in range(32):
      img_batch = batch[0]
      img_index = e # random image from the image_batch taken from ImageDataGenerator
      img_array = (img_batch[img_index] * 255).astype(np.uint8)
      resized_img = np.asarray(resize(img_array, (224, 224))).astype(np.uint8)
      # np.seterr(divide='ignore', invalid='ignore')
      # resized_img = resized_img / 255

      fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(14, 14), constrained_layout=True)
      axs[0].imshow(img_array)
      axs[1].imshow(resized_img)
      prediction = batch[1][img_index]
      for i in range(4):
        if prediction[i] == 1:
          if i == 0:
            print("Glioma")
          elif i == 1:
            print("Meningioma")
          elif i == 2:
            print("Normal")
          elif i == 3:
            print("Pituitary")
      print(predictions1[prednum])
      index = np.argmax(predictions1[prednum])
      prednum += 1
      if index == 0:
        print("Glioma")
      elif index == 1:
        print("Meningioma")
      elif index == 2:
        print("Normal")
      elif index == 3:
        print("Pituitary")

      # Perform Grad-CAM
      heatmap = grad_cam(resized_img)

      # Resize the heatmap to match the input image size
      heatmap = cv2.resize(heatmap, (resized_img.shape[1], resized_img.shape[0]))

      # Normalize the heatmap
      heatmap = (heatmap - np.min(heatmap)) / (np.max(heatmap) - np.min(heatmap) + 1e-10)

      # Convert to the range [0, 255] for visualization
      heatmap = (255 * heatmap).astype("uint8")

      # Apply a colormap
      heatmap_colored = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

      # Superimpose the heatmap on the original image
      superimposed_img = cv2.addWeighted(resized_img, 1, heatmap_colored, 0.6, 0) # first num and second num is aplha and beta, which is how much is used from each respective image

      # Display the result
      axs[2].imshow(superimposed_img)
      plt.show()
      print("image: " + str(prednum))
      print("--------------------------------------------------------")

def gradcam(model, img):
  with GradientTape() as tape:
    last_convlayer = model.get_layer('BlockGroup5__block_2__conv_3')
    model_in = Model([model.inputs], [model.outputs, last_convlayer.output])
    model_out, last_convlayer = model_in(img.reshape(1,224,224,3))
    class_out = model_out[:, np.argmax(model_out[0])] # colon means collect all
    grads = tape.gradient(class_out, last_convlayer)
    avg_grad = K.mean(grads, axis = (0, 1, 2))
  heatmap = tf.reduce_mean(tf.multiply(avg_grad, last_convlayer), axis = -1) #determine activation (hot area)
  heatmap = np.maximum(heatmap, 0) #intensifies hotter areas
  #np.seterr(divide = '')
  heatmap /= np.max(heatmap) # keeps numbers in a certain range of [0,1]
  heatmap = heatmap.reshape(8,8) #condense heatmap into kernel for overlay

  heatmap = cv2.resize(heatmap, (img.shape[0], img.shape[1]))
  colormap = cv2.applyColorMap(np.uint8(heatmap * 255), cv2.COLORMAP_JET)

  superimposed_img = ((colormap + img) * 180).astype(np.uint8) #overlay heat onto original, 180 is intesnity coefficient

  plt.imshow(superimposed_img)
  plt.show()

grad_cam(model, resized_img)
